addition to outreach team
FranBonath/nf-co.re pull request #1
Opened 2022-05-09 15:19 UTC by FranBonath

adding myself and Xesus to outreach, moved Renuka to Alumni

2022-05-12 14:05 UTC, FranBonath commented
@ewels there seem to be some broken links that I didn't touch? Can this PR be merged?

2022-05-12 15:16 UTC, ewels commented on markdown/about.md
> +- Xesús M. Abalo
Let's wait until he gets registered on GitHub :octocat: 👍🏻

2022-05-16 08:22 UTC, ewels requested changes
Minor, nearly there!

2022-05-16 08:22 UTC, ewels commented on markdown/about.md
> +- [@renbot-bio](https://github.com/renbot-bio): Renuka Kudva
Technically not core team. Can you perhaps just adjust the intro text to be less specific?

```markdown
The following people have earned their place in the nf-core alumni hall of fame:
```

2022-05-16 08:22 UTC, ewels commented on markdown/about.md
> +- [@Xesus-Abalo](https://github.com/Xesus-Abalo) Xesús M. Abalo
🤓 
```suggestion
- [@Xesus-Abalo](https://github.com/Xesus-Abalo): Xesús M. Abalo
```

2022-05-16 08:39 UTC, ewels approved these changes
![Crocodile Hunter Yes](https://media.giphy.com/media/k2bbmbmvUo7gA/giphy.gif)

2022-05-16 08:41 UTC, ewels commented
oh, wait - haha. Wondered why I couldn't merge then realised that this PR isn't against the @nf-core fork 😅  You're just asking to merge against your own `master` branch..

There should be an edit button at the top where you can change the target branch, maybe you can also change the repot that it's pointing to? If not, you'll want to close this (without merging) and then open up a new PR against nf-core/nf-co.re (not FranBonath/nf-co.re).

You might need to click this link: 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/465550/168553551-97a42e2c-d414-4a59-8c22-6b244b2e532a.png">

To be able to see this dropdown for the base repo:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/465550/168553607-bc925273-4c76-4ee2-ba7b-d2c194cd173f.png">

2022-05-16 08:58 UTC, FranBonath commented
PR to wrong depo

2022-05-16 08:58 UTC, closed without merging